name: Android CI

on:
  pull_request:

jobs:
  build:
    name: Build with Gradle
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildType: [debug, release]
        flavor: [emulator, physical]
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -x test
  capture:
    name: Capture with Roborazzi
    uses: ./.github/workflows/capture_test.yml

