name: Android CI

on:
  pull_request:
#    types:
#      - labeled

jobs:
  build:
    name: Build with Gradle
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'BuildTest' }}
    strategy:
      matrix:
        buildType: [debug, release]
        flavor: [emulator, physical]
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -x test
  capture:
    name: Capture with Roborazzi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.9.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: test
        run: |
          # Create screenshots
          ./gradlew app:recordRoborazziEmulatorDebug --stacktrace

      # Upload screenshots to GitHub Actions Artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: golden_screenshots
          path: app/build/outputs/roborazzi
          retention-days: 30

