name: Ktlint Format

on:

jobs:
  build:
    name: Build with Gradle
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildType: [debug, release]
        flavor: [emulator, physical]
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew ktlintFormat
      - uses: peter-evans/create-pull-request@v5
        with:
          token: ${{secrets.MY_GITHUB_TOKEN}}
          commit-message: Ktlint auto format
          branch: auto-formatted/
          branch-suffix: timestamp
          base: ${{github.head_ref}}
          delete-branch: true
          title: Ktlint auto format
          body: |
            created by github actions

