name: Actions Close Comment

permissions:
  pull-requests: write

on:
  pull_request:
    types: [closed]

jobs:
  comment:
    name: comment on closed pr
    runs-on: ubuntu-latest
    steps:
      - name: print object info for debug
        run: |
          echo "github.event.pull_request"
          echo ${{toJson(github.event.pull_request)}}
      - name: comment on closed pr
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            PR Closed ${{github.event.pull_request.actor}}
            Hello World
            PR Closed ${{github.event.pull_request}}
