name: Ktlint Check

on:
  pull_request:
    types:
      - opened
      - synchronize
permissions:
  pull-requests: write

jobs:
  ktlint-check:
    name: Run Ktlint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3.9.0
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Install Ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/latest/download/ktlint
          chmod +x ktlint
          sudo mv ktlint /usr/local/bin/
        shell: bash

      - name: Run Ktlint
        id: ktlint
        run: |
          ktlint --reporter=checkstyle --reporter=checkstyle,output=build/report/ktlint-report.xml,format=sarif

      - uses: actions/upload-artifact@v3
        with:
          name: report
          path: build/report/
          retention-days: 30

#コメントするテスト
#      - name: create text file
#        run: |
#          echo "GithubActions" > message.txt
#      - name: Comment PR

#        if: steps.ktlint.outputs.ktlint-result != 'null'
#        uses: thollander/actions-comment-pull-request@v2
#        with:
#          filePath: message.txt
#コメントするテスト

#      - name: Comment on PR if issues found
#        if: steps.ktlint.outputs.ktlint-result != 'null'
#        run: |
#          COMMENT="#### Ktlint Issues\n\`\`\`xml\n$(cat ktlint-checkstyle.xml)\n\`\`\`"
#          echo "$COMMENT" > comment.md
#          echo "Commenting on the PR..."
#          curl -sSL -H "Authorization: Bearer $GITHUB_TOKEN" -H "Content-Type: application/json" \
#            -X POST -d "{\"body\":\"$COMMENT\"}" \
#            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
